# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      include:
        - tool/**
        - pubspec.yaml
        - lib/**
        - templates/**
    builders:
      stagehand:
        generate_for:
          - lib/src/cli_app.dart
          - lib/src/generators/*.dart
        enabled: true

builders:
  stagehand:
    import: "tool/builder.dart"
    builder_factories: ["stagehandBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
