name: __projectName__
description: A simple AngularDart app
version: 0.0.1
#homepage: https://www.example.com
#author: __author__ <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: ^3.0.0-alpha

dev_dependencies:
  angular_test: ^1.0.0-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

# FIXME: temporary, until 3.0.0-beta+1 is released
dependency_overrides:
  angular_test: 1.0.0-alpha+6
  angular2:
    git:
      url: https://github.com/dart-lang/angular2.git
      ref: 3.0.0-alpha+1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
