# Google-default lint rules as defined in package:pedantic (v1.4.0).
# See: https://github.com/dart-lang/pedantic for details and the
# latest ruleset.
linter:
  # For additional lint rules and documentation, see 
  # http://dart-lang.github.io/linter/lints.
  rules:
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - unawaited_futures
    - valid_regexps

# The equivalent rules can be included by removing this list
# and including the pedantic options file like this:
#
# include: package:pedantic/analysis_options.yaml
# 
# (Note that this will require you to add package:pedantic
# to your pubspec.yaml.)

analyzer:
#   exclude:
#     - path/to/excluded/files/**
