// Copyright (c) 2018, Google Inc. Please see the AUTHORS file for details.
// All rights reserved. Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

const List<String> data = const [
  '.gitignore',
  'text',
  '''IyBGaWxlcyBhbmQgZGlyZWN0b3JpZXMgY3JlYXRlZCBieSBwdWIKLmRhcnRfdG9vbC8KLnBhY2th
Z2VzCi5wdWIvCmJ1aWxkLwojIFJlbW92ZSB0aGUgZm9sbG93aW5nIHBhdHRlcm4gaWYgeW91IHdp
c2ggdG8gY2hlY2sgaW4geW91ciBsb2NrIGZpbGUKcHVic3BlYy5sb2NrCgojIERpcmVjdG9yeSBj
cmVhdGVkIGJ5IGRhcnRkb2MKZG9jL2FwaS8K''',
  'CHANGELOG.md',
  'text',
  'IyMgMC4wLjEKCi0gSW5pdGlhbCB2ZXJzaW9uLCBjcmVhdGVkIGJ5IFN0YWdlaGFuZAo=',
  'README.md',
  'text',
  '''IyBfX3Byb2plY3ROYW1lX18KCkEgd2ViIHNlcnZlciBidWlsdCB1c2luZyBbU2hlbGZdKGh0dHBz
Oi8vcHViLmRhcnRsYW5nLm9yZy9wYWNrYWdlcy9zaGVsZikuCgpDcmVhdGVkIGZyb20gdGVtcGxh
dGVzIG1hZGUgYXZhaWxhYmxlIGJ5IFN0YWdlaGFuZCB1bmRlciBhIEJTRC1zdHlsZQpbbGljZW5z
ZV0oaHR0cHM6Ly9naXRodWIuY29tL2RhcnQtbGFuZy9zdGFnZWhhbmQvYmxvYi9tYXN0ZXIvTElD
RU5TRSkuCg==''',
  'analysis_options.yaml',
  'text',
  '''YW5hbHl6ZXI6CiAgc3Ryb25nLW1vZGU6IHRydWUKIyAgIGV4Y2x1ZGU6CiMgICAgIC0gcGF0aC90
by9leGNsdWRlZC9maWxlcy8qKgoKIyBMaW50IHJ1bGVzIGFuZCBkb2N1bWVudGF0aW9uLCBzZWUg
aHR0cDovL2RhcnQtbGFuZy5naXRodWIuaW8vbGludGVyL2xpbnRzCmxpbnRlcjoKICBydWxlczoK
ICAgIC0gY2FuY2VsX3N1YnNjcmlwdGlvbnMKICAgIC0gaGFzaF9hbmRfZXF1YWxzCiAgICAtIGl0
ZXJhYmxlX2NvbnRhaW5zX3VucmVsYXRlZF90eXBlCiAgICAtIGxpc3RfcmVtb3ZlX3VucmVsYXRl
ZF90eXBlCiAgICAtIHRlc3RfdHlwZXNfaW5fZXF1YWxzCiAgICAtIHVucmVsYXRlZF90eXBlX2Vx
dWFsaXR5X2NoZWNrcwogICAgLSB2YWxpZF9yZWdleHBzCg==''',
  'bin/server.dart',
  'text',
  '''aW1wb3J0ICdkYXJ0OmlvJzsKCmltcG9ydCAncGFja2FnZTphcmdzL2FyZ3MuZGFydCc7CmltcG9y
dCAncGFja2FnZTpzaGVsZi9zaGVsZi5kYXJ0JyBhcyBzaGVsZjsKaW1wb3J0ICdwYWNrYWdlOnNo
ZWxmL3NoZWxmX2lvLmRhcnQnIGFzIGlvOwoKbWFpbihMaXN0PFN0cmluZz4gYXJncykgYXN5bmMg
ewogIHZhciBwYXJzZXIgPSBuZXcgQXJnUGFyc2VyKCkKICAgIC4uYWRkT3B0aW9uKCdwb3J0Jywg
YWJicjogJ3AnLCBkZWZhdWx0c1RvOiAnODA4MCcpOwoKICB2YXIgcmVzdWx0ID0gcGFyc2VyLnBh
cnNlKGFyZ3MpOwoKICB2YXIgcG9ydCA9IGludC50cnlQYXJzZShyZXN1bHRbJ3BvcnQnXSk7Cgog
IGlmIChwb3J0ID09IG51bGwpIHsKICAgIHN0ZG91dC53cml0ZWxuKAogICAgICAgICdDb3VsZCBu
b3QgcGFyc2UgcG9ydCB2YWx1ZSAiJHtyZXN1bHRbJ3BvcnQnXX0iIGludG8gYSBudW1iZXIuJyk7
CiAgICAvLyA2NDogY29tbWFuZCBsaW5lIHVzYWdlIGVycm9yCiAgICBleGl0Q29kZSA9IDY0Owog
ICAgcmV0dXJuOwogIH0KCiAgdmFyIGhhbmRsZXIgPSBjb25zdCBzaGVsZi5QaXBlbGluZSgpCiAg
ICAgIC5hZGRNaWRkbGV3YXJlKHNoZWxmLmxvZ1JlcXVlc3RzKCkpCiAgICAgIC5hZGRIYW5kbGVy
KF9lY2hvUmVxdWVzdCk7CgogIHZhciBzZXJ2ZXIgPSBhd2FpdCBpby5zZXJ2ZShoYW5kbGVyLCAn
bG9jYWxob3N0JywgcG9ydCk7CiAgcHJpbnQoJ1NlcnZpbmcgYXQgaHR0cDovLyR7c2VydmVyLmFk
ZHJlc3MuaG9zdH06JHtzZXJ2ZXIucG9ydH0nKTsKfQoKc2hlbGYuUmVzcG9uc2UgX2VjaG9SZXF1
ZXN0KHNoZWxmLlJlcXVlc3QgcmVxdWVzdCkgPT4KICAgIG5ldyBzaGVsZi5SZXNwb25zZS5vaygn
UmVxdWVzdCBmb3IgIiR7cmVxdWVzdC51cmx9IicpOwo=''',
  'pubspec.yaml',
  'text',
  '''bmFtZTogX19wcm9qZWN0TmFtZV9fCmRlc2NyaXB0aW9uOiBBIHdlYiBzZXJ2ZXIgYnVpbHQgdXNp
bmcgdGhlIHNoZWxmIHBhY2thZ2UuCiMgdmVyc2lvbjogMS4wLjAKI2hvbWVwYWdlOiBodHRwczov
L3d3dy5leGFtcGxlLmNvbQojYXV0aG9yOiBfX2F1dGhvcl9fIDxlbWFpbEBleGFtcGxlLmNvbT4K
CmVudmlyb25tZW50OgogIHNkazogJz49Mi4wLjAtZGV2LjQ4LjAgPDIuMC4wJwoKZGVwZW5kZW5j
aWVzOgogIGFyZ3M6IF4xLjQuMgogIHNoZWxmOiBeMC43LjIKCiNkZXZfZGVwZW5kZW5jaWVzOgoj
ICB0ZXN0OiBeMC4xMi4zMAo='''
];
